import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript, MantineProvider, useSafeMantineTheme } from "@mantine/core";
import "@mantine/core/styles.css";
import { GoPlusCircle } from "react-icons/go";

import { Avatar } from "@mantine/core";
import Button from "@/components/Button";
import { BsPlusCircleDotted } from "react-icons/bs";
import { useState } from "react";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const   RootLayout =  async({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)=> {
  const session = await auth();


  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className="w-full flex  ">
        <MantineProvider>
          <div className="flex w-full ">
            <div className="w-1/3 border-r-2 h-screen ">
              <div id="Profile" className=" border-b-2 m-2 flex space-x-4 p-8">
                <Avatar radius="lg" src={session?.user?.image} size="lg" />
                <div className="flex  justify-center flex-col">
                  <p>{ session ? session.user?.name: "Guest" }</p>
                  <p>Premium</p>
                </div>
              </div>
              <div className="relative  ">
                <div className="flex overflow-y-auto overflow-x-hidden  space-y-2 items-center w-full flex-col ">
                  <Button label="Tasks" />
                  <Button label="Calender" />
                  <Button label="Task 1" />
                  <Button label="Task 2" />
                  <Button>
                    <BsPlusCircleDotted size={30} />
                  </Button>
                </div>
              </div>
            </div>

            <div className="w-full h-full">{children}</div>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
export default RootLayout